name: Build artifact

on:
  push:
    branches: [master, custom]
  pull_request:
    branches: [master, custom]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run cross-env ANALYTICS_API_SECRET=${{ secrets.ANALYTICS_API_SECRET }} yarn run package
      - run: 7z a release.zip release

      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip
